### ISSUE TITLE
使用内联语法写样式时会出现额外字符

### ISSUE THREAD

**Issue by jide123456** [fisker/fis3-parser-pug#1]
![image](https://cloud.githubusercontent.com/assets/21555863/21599291/5cbf0e26-d1a5-11e6-9633-ecec55f4da27.png)

![image](https://cloud.githubusercontent.com/assets/21555863/21599295/6c1a0376-d1a5-11e6-9a42-43ab28d27581.png)

![image](https://cloud.githubusercontent.com/assets/21555863/21599305/90fbb90a-d1a5-11e6-859e-af8478a811c7.png)

如图一所示 inline-style-placeholder    不知道是什么东西

**Comment by fisker** [comment]
感觉应该是fis加的  晚点看 忙 :(

**Comment by jide123456** [comment]
@fisker    谢谢， 已经解决了 ，  是我配置的问题。

我之前匹配的是 ‘/view/两个星' ， 改成 '/view/两个星.pug' 就好了 。  (两个星指**)
